name: ping-pong
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync
        uses: make sync

      - name: Build
        run: make build
  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run ping pong on localhost
        run: make ping-pong

      - name: Lint
        run: make lint
  tests:
    runs-on: ubuntu-latest
    needs: [build, run]
    steps:
      - name: Run tests
        run: make tests
